from collections.abc import Callable, Coroutine
from typing import Any, Protocol

from harpi.domain.track_metadata import TrackMetadata


class AudioResolverProtocol(Protocol):
    async def resolve(self, link: str) -> TrackMetadata: ...
    async def resolve_stream(self, track: TrackMetadata) -> str: ...


class AudioPlayerProtocol(Protocol):
    background_tracks: list[TrackMetadata]
    is_paused: bool = False
    volume: float
    background_volume: float

    @property
    def playing(self) -> TrackMetadata | None: ...
    @property
    def position(self) -> float | None: ...
    @property
    def is_connected(self) -> bool: ...
    async def play(
        self,
        track: TrackMetadata,
        on_finish: Callable[[], Coroutine[Any, Any, None]] | None = None,
    ) -> None: ...
    async def pause(self) -> None: ...
    async def resume(self) -> None: ...
    async def stop(self) -> None: ...
    def set_volume(self, volume: float) -> None: ...
    def set_background_volume(self, volume: float) -> None: ...
    def set_ducking(self, duck_level: float) -> None: ...
    async def add_background_source(self, track: TrackMetadata) -> None: ...
    def remove_background_source(self, index: int) -> TrackMetadata: ...
    def set_voice_client(self, voice_client) -> None: ...
    async def connect(self, channel) -> None: ...


class AudioPlayerFactoryProtocol(Protocol):
    def create_player(self, resolver: AudioResolverProtocol) -> AudioPlayerProtocol: ...
