from collections.abc import Callable, Coroutine
from typing import Any, Protocol

from harpi.domain.track import Track


class AudioResolverProtocol(Protocol):
    async def resolve(self, link: str) -> Track: ...


class AudioPlayerProtocol(Protocol):
    background_tracks: list[Track]
    is_paused: bool = False
    is_stopped: bool = False

    @property
    def playing(self) -> Track | None: ...
    @property
    def position(self) -> float | None: ...
    async def play(self, track: Track, on_finish: Callable[[], Coroutine[Any, Any, None]] | None = None) -> None: ...
    async def pause(self) -> None: ...
    async def resume(self) -> None: ...
    async def stop(self) -> None: ...
